### ISSUE TITLE
RWC 2015

### ISSUE THREAD

**Issue by Cclleemm** [fcote/worldcup#2]
@clemh78 Salut, penses tu que cet outils peut être adapté et utilisé pour la coupe du monde de rugby ? Je ne l'ai pas essayé encore mais je pense que c'est exactement le même fonctionnement même s'il est plus dur d'estimer le score exacte d'un match de rugby...

**Comment by clemh78** [comment]
Je ferme le ticket, le projet a été adapté pour le rugby (dans la branche rugby).
